# Disable the newline at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

# ãƒãƒƒãƒ†ãƒªãƒ¼æ®‹é‡ãŒ0ï¼…ã€œ10ï¼…ã®é–“ã¯ã€Œå¤ªå­—ã®èµ¤è‰²ã€ã‚¹ã‚¿ã‚¤ãƒ«ã‚’åˆ©ç”¨ã™ã‚‹
[[battery.display]]
threshold = 10
style = "bold red"

# ãƒãƒƒãƒ†ãƒªãƒ¼æ®‹é‡ãŒ10ï¼…ã€œ30ï¼…ã®é–“ã¯ã€Œå¤ªå­—ã®é»„è‰²ã€ã‚¹ã‚¿ã‚¤ãƒ«ã‚’åˆ©ç”¨ã™ã‚‹
[[battery.display]]
threshold = 30
style = "bold yellow"

# git
[git_branch]
symbol = "ï˜ "
truncation_length = 15
truncation_symbol = "..."

[git_commit]
disabled = false
commit_hash_length = 4

# golang
[golang]
format = "[via î˜¦ $version ](bold cyan)"

# dart
[dart]
format = "[via î˜ $version ](bold cyan)"

# directory
[directory]
format = "[ï“ $path ](bold cyan)"
truncation_length = 10
truncation_symbol = "â€¦/"
